sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
env:
  global:
  - secure: BYZxrcEbzzlxpLzCzNeByOc56uoWD/eebnO7aey0MpIvvA0py9HxIQx/dUoYOafQgZKqI6GMJqKd2sPHoSzYk7c0oDFeFtjsIJdDzhxm333SNhQyWbQ/q2w67a8irRtCnOpf/rPNJyudN9+up69hM+Nn2l196i6D6/hIBzMstg8SXgctADBb1pmHsyGqOXIn2tq1ezzHwf6DZRjuHWD7bRj3zv3ZjPYZHY08T/1ekDNp2qTRXYBhwG/4VPlt3hEQJSTBlv94qgFTADSSLHbctTQg4Rj/UnJciszNupb7uN2NR4LfqYGsASCT6H3yhnQZND9Uk+4TV+Er7/TKZO5dAL8jmnXtvihvopEjulWbaykFli+T0Np7qbUi9PeqxjoADZVeUO4OEH364qofVy5wiHygGj3F3i60j723lZqqBtyUkficN3e1tRYVu24aIbUve9GMl1Vdi34L7WewW6FDAweMLwCWGiANlB52NPa+cDjLIwhMMEl2TQfYNdLwP88a+CxJWDbgYvyWOSn5HsyWUU6hZb88w3ZCaobDDHIgyKLge3UUl20tOi06Vtu1de5/LSVpCbUcQ8YGAjXldkZXlgCsODKL9oU5yqwBLEEDCon9xEZlQNHpLhhQBNbqK7dreO5xHf6+q3uTkqyfaYgcEmqDTE4XhIuNZfMPd58Hm+c=
  - secure: UKj6xoFSN16Vae+2zUz+B7Gg5k8dNKCosizqCO0QFvShGhb3Jx5OU9dKjaK96M19YT+ojviM205VLZgYXoyQBsq4mlfMo54/EndgPiHZy9D4FGyY1zhl0VrTTrrX5RaF0McyRkKENbIN70i+sX24bU0lAfBvO+ABrFiQg4mlxPWSZu6D9EKiTVz4vQvHBdTODoa/XoVh9ZyQBx5PowOhLHCGkUIe/rEoC1uI7Y+bTVSTXOVNZojpO64L3CxjqRWkaVVAoVAekOTlHjxKYAC4Rbvf7TZmTbgrSOHLVBLJjQv5qbWS9A2kjaMYuWyySZIP6r936PJKlHN3I42N8X8riQgsof24LTy1j/8lmNgtqMDKd3i9IWMWC5Lp5H7FDHTfI9O1PCNY/cAL3MNq6gCPdaiLOxFX11vBaH9C0Z4nWQ3XDo1kaTjlIV6P5zeckUEq5CvhNYfh5ycL3rs7Yyc4AivTQgUA137umGR3e/ju3QOEQbYnfmqdFTWvENygXLfWPxJhZVZxZPKbQYx7CEujTw3o+nSfnan5yxcvF+Wh224qHEwf3Z6NPkTV6WpYpldHlcVARgk60SFS5T657RsMBKu5D8VF6Ay2PGiUCQ9Aoo7GbmKCkRw6nUCiv/UguaCqy9KdjmnoYAk1PL6dZfCyKEkrkPUqkVJN2jDrmYbKV88=
